### ISSUE TITLE
Inverted red and blue channels (wrong YARP <-> OpenCV conversion)

### ISSUE THREAD

**Issue by jchevrie** [robotology/segmentation#10]
The rgb images sent to the output ports of the lbpExtract module have inverted red and blue channels.

The reason comes from an invalid conversion syntax, for example
https://github.com/robotology/segmentation/blob/b418a24d78de7bc50e23894664eec29ccee08046/lbpExtract/src/lbpExtract.cpp#L732
It should be changed to something like
`outOrig = fromCvMat<PixelRgb>(imgMat);`

I can fix it for the `lbpExtract` module, and also in the other modules of this repo (I did not check yet if the same issue also appears for these), but maybe you are also aware of other repos where the same syntax is present and should be fixed as well.

**Comment by pattacini** [comment]
Unfortunately, the introduction of `yarp::cv` routines came at the cost of this unexpected problem of inverted colors. Therefore, after updating to the use of such a new YARP wrapper service, there might be lots of places in robotology requiring our attention. Today, we fixed the red-ball demo, for example.

What I did was checking that, within the IOL pipeline, the segmented output of this module was in true colors (CARVE demo). Of course, I might have missed other points.

cc @vtikha @Nicogene

**Comment by Nicogene** [comment]
> `outOrig = fromCvMat<PixelRgb>(imgMat);`

I confirm that this should do the job :+1:

**Comment by jchevrie** [comment]
In my case when I tested yesterday with the IOL pipeline the output of the lbpExtract was color inverted.
I will check if I didn't miss some recent modifications of the `YARP` and `segmentation` repos, maybe my forks are not up to date.

**Comment by pattacini** [comment]
Yeah please double check, it might be also that the code on R1-mk2 is not up-to-date (this would be weird then) and I provided wrong info.

**Comment by vtikha** [comment]
@jchevrie any updates on this?

**Comment by jchevrie** [comment]
Yes, the issue is still present with the last version of `segmentation` on the robot.
The input image is correct but the output images have blue and red channels inverted.

I think a lot of the changes introduced in https://github.com/robotology/segmentation/commit/9b16e4580d2223d89d4fb96bdd9a93fe8c1b405f do not really work as intended because `toCvMat` and `fromCvMat` do not behave the same way `getIplImage` did.
