### ISSUE TITLE
lbpExtract does not extract contours with OpenCV-3.x.y

### ISSUE THREAD

**Issue by pattacini** [robotology/segmentation#3]
##### Problem
Together with @gregoire-pointeau and @vtikha we realized that `lbpExtract` compiled against `OpenCV-3.x.y` does extract the binary patterns from the image but not the contours. This should be due to how the new API in `OpenCV` are intended to work.

##### Workaround
While we will be investigating this issue to find the proper fix, it is still possible to use `lbpExtract` compiled against `OpenCV-2.x.y`. In fact, it's perfectly doable to use two versions of `OpenCV` side-by-side on the same system.

**Comment by vtikha** [comment]
Problem solved :smile: 
```LbpExtract``` is now good to go with ```Opencv-3.x.y``` without breaking compatibility with ```OpenCV-2.x.y```

**Comment by pattacini** [comment]
Great :+1:

**Comment by Tobias-Fischer** [comment]
Thanks @vtikha!
